import type { Lesson } from "./types";

/**
 * LESSON CONTENT ANALYSIS
 * -----------------------
 * The AI Coach must base everything on what's actually in the lesson — not
 * generic filler. A video's "contents" = its transcript (auto-generated by
 * Whisper/Mux in production) plus any text blocks and media captions the admin
 * added. This module reads that corpus and produces summaries + quizzes that
 * are genuinely derived from it.
 *
 * Swap-in point for real AI: pass `readLesson(lesson).corpus` to an LLM for
 * richer output. The local extraction below keeps it working with no backend.
 */

const STOP = new Set(
  "a an the and or but if then so to of in on at for with as is are was were be been being this that these those it its your you they them their our we i he she his her about into over under can will just not no yes do does what when how why who which from by has have had more most than".split(
    " "
  )
);

/** Domain terms we recognize in insurance training content. */
const GLOSSARY = [
  "IUL", "indexed universal life", "term life", "whole life", "cash value",
  "premium", "death benefit", "beneficiary", "underwriting", "policy",
  "coverage", "objection", "objection handling", "prospecting", "closing",
  "referral", "recruiting", "team building", "retirement", "licensing",
  "fixed income", "tax-advantaged", "guarantee", "risk", "value",
];

export interface LessonKnowledge {
  title: string;
  transcript: string;
  textBlocks: string[];
  captions: string[];
  corpus: string;
  sentences: string[];
  terms: string[];
  hasContent: boolean;
  sources: { hasTranscript: boolean; textCount: number; mediaCount: number };
}

function sentencesOf(text: string): string[] {
  return text
    .replace(/\s+/g, " ")
    .split(/(?<=[.!?])\s+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 18);
}

function keyTerms(corpus: string, title: string): string[] {
  const lower = corpus.toLowerCase();
  const found = new Set<string>();

  // 1) domain glossary terms actually present in the content
  for (const g of GLOSSARY) {
    if (lower.includes(g.toLowerCase())) found.add(g);
  }

  // 2) frequent meaningful words from the corpus itself
  const freq = new Map<string, number>();
  for (const raw of (title + " " + corpus).toLowerCase().match(/[a-z][a-z-]{3,}/g) ?? []) {
    if (STOP.has(raw)) continue;
    freq.set(raw, (freq.get(raw) ?? 0) + 1);
  }
  [...freq.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 6)
    .forEach(([w]) => found.add(w));

  return [...found].slice(0, 8);
}

/**
 * Whether the coach can trust the transcript for THIS lesson's video.
 * An AI can only "watch" a video via its transcript, so if a real video has
 * been added but the transcript wasn't written/generated for it, the coach must
 * NOT summarize the stale text — it would describe the wrong video.
 */
export function lessonCoachState(lesson: Lesson) {
  const videoBlock = lesson.blocks.find(
    (b) => b.type === "video" && b.src.trim()
  );
  const hasRealVideo = !!videoBlock;
  const primaryVideoSrc = videoBlock?.src ?? "";
  const transcriptMatches = !hasRealVideo
    ? true // no uploaded video to contradict — analyze whatever text exists
    : !!lesson.transcript.trim() && lesson.transcriptVideoSrc === primaryVideoSrc;
  return { hasRealVideo, primaryVideoSrc, transcriptMatches };
}

export function readLesson(lesson: Lesson): LessonKnowledge {
  const textBlocks = lesson.blocks
    .filter((b) => b.type === "text" && b.caption.trim())
    .map((b) => b.caption.trim());
  const captions = lesson.blocks
    .filter((b) => b.type !== "text" && b.caption.trim())
    .map((b) => b.caption.trim());
  const transcript = (lesson.transcript ?? "").trim();

  const corpus = [transcript, ...textBlocks, ...captions]
    .filter(Boolean)
    .join(". ");
  const sentences = sentencesOf(corpus);
  const terms = keyTerms(corpus, lesson.title);

  return {
    title: lesson.title,
    transcript,
    textBlocks,
    captions,
    corpus,
    sentences,
    terms,
    hasContent: corpus.replace(/\s/g, "").length > 30,
    sources: {
      hasTranscript: transcript.length > 0,
      textCount: textBlocks.length,
      mediaCount: captions.length,
    },
  };
}

/** Rank sentences by how many key terms they contain (extractive summary). */
function rankSentences(k: LessonKnowledge): string[] {
  return [...k.sentences]
    .map((s) => {
      const lower = s.toLowerCase();
      const score = k.terms.reduce(
        (n, t) => n + (lower.includes(t.toLowerCase()) ? 1 : 0),
        0
      );
      return { s, score };
    })
    .sort((a, b) => b.score - a.score)
    .map((x) => x.s);
}

export interface CoachSummary {
  takeaways: string[];
  actions: string[];
  concepts: string[];
}

export function summarizeLesson(lesson: Lesson): CoachSummary {
  const k = readLesson(lesson);
  const ranked = rankSentences(k);
  const takeaways = (ranked.length ? ranked : k.sentences).slice(0, 3);

  const topTerms = k.terms.slice(0, 3);
  const actions = topTerms.length
    ? topTerms.map((t) => `Be able to explain "${t}" in one sentence from memory.`)
    : ["Re-watch the lesson and write three things you learned."];

  return {
    takeaways: takeaways.length
      ? takeaways
      : ["This lesson's transcript is too short to summarize — add more content."],
    actions,
    concepts: k.terms.slice(0, 6),
  };
}

export interface QuizQuestion {
  question: string;
  options: string[];
  correct: number;
  source: string; // the line of content this came from
}

const pick = <T,>(arr: T[], seed: number) => arr[((seed % arr.length) + arr.length) % arr.length];

/** Build quiz questions straight out of the lesson's own sentences/terms. */
export function generateQuiz(lesson: Lesson, count = 3): QuizQuestion[] {
  const k = readLesson(lesson);
  if (!k.hasContent) return [];

  const questions: QuizQuestion[] = [];
  const usedTerms = new Set<string>();

  // 1) fill-in-the-blank from real sentences that contain a key term
  for (const sentence of rankSentences(k)) {
    if (questions.length >= count) break;
    const term = k.terms.find(
      (t) => sentence.toLowerCase().includes(t.toLowerCase()) && !usedTerms.has(t)
    );
    if (!term) continue;
    usedTerms.add(term);

    const re = new RegExp(term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i");
    const blanked = sentence.replace(re, "______");

    // distractors: other terms from this lesson + glossary, not the answer
    const distractors = [...k.terms, ...GLOSSARY]
      .filter((t) => t.toLowerCase() !== term.toLowerCase())
      .filter((t, i, a) => a.findIndex((x) => x.toLowerCase() === t.toLowerCase()) === i)
      .slice(0, 8);

    const opts = [term, ...distractors.slice(0, 3)];
    // deterministic shuffle by sentence length
    const order = opts
      .map((o, i) => ({ o, r: (i + 1) * (sentence.length % 7 + 1) }))
      .sort((a, b) => a.r - b.r)
      .map((x) => x.o);

    questions.push({
      question: `Fill in the blank: "${blanked}"`,
      options: order,
      correct: order.findIndex((o) => o === term),
      source: sentence,
    });
  }

  // 2) topic question if we still need more
  if (questions.length < count && k.terms.length) {
    const answer = k.terms[0];
    const distractors = GLOSSARY.filter(
      (g) => g.toLowerCase() !== answer.toLowerCase()
    ).slice(0, 3);
    const opts = [answer, ...distractors];
    const order = opts
      .map((o, i) => ({ o, r: (i + 3) * (k.title.length % 5 + 1) }))
      .sort((a, b) => a.r - b.r)
      .map((x) => x.o);
    questions.push({
      question: `Which concept is central to this lesson?`,
      options: order,
      correct: order.findIndex((o) => o === answer),
      source: `Lesson focus: ${k.title}`,
    });
  }

  return questions.slice(0, count);
}

/** "Explain this" — explain the lesson's top concept using its own content. */
export function explainTopConcept(lesson: Lesson): {
  term: string;
  context: string;
  plain: string;
} | null {
  const k = readLesson(lesson);
  if (!k.terms.length) return null;
  const term = k.terms[0];
  const context =
    k.sentences.find((s) => s.toLowerCase().includes(term.toLowerCase())) ??
    k.sentences[0] ??
    "";
  return {
    term,
    context,
    plain: `In this lesson, "${term}" is a key idea. ${
      context || "Re-watch the section where it's introduced."
    } When you explain it to a prospect, lead with the benefit to them, then back it with one concrete fact.`,
  };
}
